#! /bin/sh

### BEGIN INIT INFO
# Provides:          BTJS3
# Required-Start:    bluetooth sshd
# Required-Stop:     bluetooth sshd
# Default-Start:     2 3 4 5
# Default-Stop:	     0 1 6 
# Short-Description: Bluetooth Gamepad Bridge
# Description:       Gamepad to Mindstorm EV3 
#                    Bluetooth bridge
### END INIT INFO
#. /lib/lsb/init-functions

#/root/run_js.sh

#set -e

case "$1" in
	start|force-reload|restart|reload)
		/root/BTJS3.sh
	;;
  	stop|status)
	;;
	*)
	echo "Usage: $N {start|stop|restart|force-reload|status}" >&2
	exit 1
	;;
esac

exit 0
